/*
 * Int.c
 *
 *  Created on: 26-04-2022
 *      Author: Cristobal
 */

#include "Int.h"

void Int_Init(void)
{
	// HABILITAMOS EL RELOJ DE LAS INTERRUPCIONES
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	// PC ES UNA INTERRUPCION
	SYSCFG ->EXTICR[3] &= ~(SYSCFG_EXTICR4_EXTI13);
	SYSCFG ->EXTICR[3] &= ~(SYSCFG_EXTICR4_EXTI13_PC);
	// NO ENMASCARAR
	EXTI ->IMR |= EXTI_IMR_IM13;
	EXTI ->EMR |= EXTI_EMR_EM13;
	// FLANCO DESCENDENTE
	EXTI ->FTSR |= EXTI_FTSR_TR13;
	// FLANCO ASCENDENTE DESHABILITADO
	EXTI ->RTSR &= ~(EXTI_RTSR_TR13);
	// PRIORIDAD
	NVIC_SetPriority(EXTI15_10_IRQn,1);
	// HABILITAR
	NVIC_EnableIRQ(EXTI15_10_IRQn);
}
